
0.00 🟢
1157+ model.cell.slide: 3.0 ()
   659+ shader.cell.slide: 2.625 (cell.slide)
      662+ cell.slide.on: 1.0 (cell.slide, cell.slide)

⟹ pipeline fixup after:
draw   (slide)  -> slide
slide  (draw)   -> color
color  (slide)  -> flatmap
flatmap(color)  -> plato
plato  (flatmap)-> nil

         650+ cell.melt.on: 0.0 (cell.slide, cell.slide, slide.on)
         656🏁 cell.tunl.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         668🏁 cell.fred.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         674🏁 cell.zha.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         644🏁 cell.ave.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         636🏁 cell.fade.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
1157+ model.cell.slide: 3.0 ()
   659+ shader.cell.slide: 2.625 (cell.slide)
      662+ cell.slide.on: 1.0 (cell.slide, cell.slide)
         650+ cell.melt.on: 0.0 (cell.slide, cell.slide, slide.on)
         656🏁 cell.tunl.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         668🏁 cell.fred.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         674🏁 cell.zha.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         644🏁 cell.ave.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         636🏁 cell.fade.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
1157+ model.cell.slide: 3.0 ()
   659+ shader.cell.slide: 2.625 (cell.slide)
      662+ cell.slide.on: 1.0 (cell.slide, cell.slide)
         650+ cell.melt.on: 0.0 (cell.slide, cell.slide, slide.on)
         656🏁 cell.tunl.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         668🏁 cell.fred.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         674🏁 cell.zha.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         644🏁 cell.ave.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         636🏁 cell.fade.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
1157+ model.cell.slide: 3.0 ()
   659+ shader.cell.slide: 2.625 (cell.slide)
      662+ cell.slide.on: 1.0 (cell.slide, cell.slide)
         650+ cell.melt.on: 0.0 (cell.slide, cell.slide, slide.on)
         656🏁 cell.tunl.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         668🏁 cell.fred.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         674🏁 cell.zha.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         644🏁 cell.ave.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         636🏁 cell.fade.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)

0.05 🛑
1157+ model.cell.slide: 3.0 ()
   659+ shader.cell.slide: 2.625 (cell.slide)
      662+ cell.slide.on: 1.0 (cell.slide, cell.slide)
         650+ cell.melt.on: 0.0 (cell.slide, cell.slide, slide.on)
         656🏁 cell.tunl.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         668🏁 cell.fred.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         674🏁 cell.zha.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         644🏁 cell.ave.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         636🏁 cell.fade.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)

0.00 🟢

0.04 🛑

0.00 🟢
1154+ model.cell.zha: 2.0 ()
   671+ shader.cell.zha: 1.7142857 (cell.zha)
      674+ cell.zha.on: 1.0 (cell.zha, cell.zha)
⟹ pipeline fixup after:
draw   (zha)    -> zha
zha    (draw)   -> color
color  (zha)    -> flatmap
flatmap(color)  -> plato
plato  (flatmap)-> nil

         668+ cell.fred.on: 0.0 (cell.zha, cell.zha, zha.on)
         656🏁 cell.tunl.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         636🏁 cell.fade.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         644🏁 cell.ave.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         662🏁 cell.slide.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         650🏁 cell.melt.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
1154+ model.cell.zha: 2.0 ()
   671+ shader.cell.zha: 1.7142857 (cell.zha)
      674+ cell.zha.on: 1.0 (cell.zha, cell.zha)
         668+ cell.fred.on: 0.0 (cell.zha, cell.zha, zha.on)
         656🏁 cell.tunl.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         636🏁 cell.fade.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         644🏁 cell.ave.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         662🏁 cell.slide.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         650🏁 cell.melt.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
1154+ model.cell.zha: 2.0 ()
   671+ shader.cell.zha: 1.7142857 (cell.zha)
      674+ cell.zha.on: 1.0 (cell.zha, cell.zha)
         668+ cell.fred.on: 0.0 (cell.zha, cell.zha, zha.on)
         656🏁 cell.tunl.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         636🏁 cell.fade.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         644🏁 cell.ave.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         662🏁 cell.slide.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         650🏁 cell.melt.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
1154+ model.cell.zha: 2.0 ()
   671+ shader.cell.zha: 1.7142857 (cell.zha)
      674+ cell.zha.on: 1.0 (cell.zha, cell.zha)
         668+ cell.fred.on: 0.0 (cell.zha, cell.zha, zha.on)
         656🏁 cell.tunl.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         636🏁 cell.fade.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         644🏁 cell.ave.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         662🏁 cell.slide.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         650🏁 cell.melt.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
1154+ model.cell.zha: 2.0 ()
   671+ shader.cell.zha: 1.7142857 (cell.zha)
      674+ cell.zha.on: 1.0 (cell.zha, cell.zha)
         668+ cell.fred.on: 0.0 (cell.zha, cell.zha, zha.on)
         656🏁 cell.tunl.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         636🏁 cell.fade.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         644🏁 cell.ave.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         662🏁 cell.slide.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         650🏁 cell.melt.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
1154+ model.cell.zha: 2.0 ()
   671+ shader.cell.zha: 1.7142857 (cell.zha)
      674+ cell.zha.on: 1.0 (cell.zha, cell.zha)
         668+ cell.fred.on: 0.0 (cell.zha, cell.zha, zha.on)
         656🏁 cell.tunl.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         636🏁 cell.fade.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         644🏁 cell.ave.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         662🏁 cell.slide.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         650🏁 cell.melt.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
1154+ model.cell.zha: 2.0 ()
   671+ shader.cell.zha: 1.7142857 (cell.zha)
      674+ cell.zha.on: 1.0 (cell.zha, cell.zha)
         668+ cell.fred.on: 0.0 (cell.zha, cell.zha, zha.on)
         656🏁 cell.tunl.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         636🏁 cell.fade.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         644🏁 cell.ave.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         662🏁 cell.slide.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         650🏁 cell.melt.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
1154+ model.cell.zha: 2.0 ()
   671+ shader.cell.zha: 1.7142857 (cell.zha)
      674+ cell.zha.on: 1.0 (cell.zha, cell.zha)
         668+ cell.fred.on: 0.0 (cell.zha, cell.zha, zha.on)
         656🏁 cell.tunl.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         636🏁 cell.fade.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         644🏁 cell.ave.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         662🏁 cell.slide.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         650🏁 cell.melt.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)

0.10 🛑
1154+ model.cell.zha: 2.0 ()
   671+ shader.cell.zha: 1.7142857 (cell.zha)
      674+ cell.zha.on: 1.0 (cell.zha, cell.zha)
         668+ cell.fred.on: 0.0 (cell.zha, cell.zha, zha.on)
         656🏁 cell.tunl.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         636🏁 cell.fade.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         644🏁 cell.ave.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         662🏁 cell.slide.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)
         650🏁 cell.melt.on: 0.0 (cell.zha, cell.zha, zha.on, fred.on)

0.00 🟢

0.10 🛑

0.00 🟢
1157+ model.cell.slide: 3.0 ()
   659+ shader.cell.slide: 2.625 (cell.slide)
      662+ cell.slide.on: 1.0 (cell.slide, cell.slide)
         650+ cell.melt.on: 0.0 (cell.slide, cell.slide, slide.on)
         656🏁 cell.tunl.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         668🏁 cell.fred.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         674🏁 cell.zha.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         644🏁 cell.ave.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         636🏁 cell.fade.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
1157+ model.cell.slide: 3.0 ()
   659+ shader.cell.slide: 2.625 (cell.slide)
      662+ cell.slide.on: 1.0 (cell.slide, cell.slide)
         650+ cell.melt.on: 0.0 (cell.slide, cell.slide, slide.on)
         656🏁 cell.tunl.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         668🏁 cell.fred.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         674🏁 cell.zha.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         644🏁 cell.ave.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         636🏁 cell.fade.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
1157+ model.cell.slide: 3.0 ()
   659+ shader.cell.slide: 2.625 (cell.slide)
      662+ cell.slide.on: 1.0 (cell.slide, cell.slide)
         650+ cell.melt.on: 0.0 (cell.slide, cell.slide, slide.on)
         656🏁 cell.tunl.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         668🏁 cell.fred.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         674🏁 cell.zha.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         644🏁 cell.ave.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         636🏁 cell.fade.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
1157+ model.cell.slide: 3.0 ()
   659+ shader.cell.slide: 2.625 (cell.slide)
      662+ cell.slide.on: 1.0 (cell.slide, cell.slide)
         650+ cell.melt.on: 0.0 (cell.slide, cell.slide, slide.on)
         656🏁 cell.tunl.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         668🏁 cell.fred.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         674🏁 cell.zha.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         644🏁 cell.ave.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         636🏁 cell.fade.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
1157+ model.cell.slide: 3.0 ()
   659+ shader.cell.slide: 2.625 (cell.slide)
      662+ cell.slide.on: 1.0 (cell.slide, cell.slide)
         650+ cell.melt.on: 0.0 (cell.slide, cell.slide, slide.on)
         656🏁 cell.tunl.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         668🏁 cell.fred.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         674🏁 cell.zha.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         644🏁 cell.ave.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         636🏁 cell.fade.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)

0.02 🛑
1157+ model.cell.slide: 3.0 ()
   659+ shader.cell.slide: 2.625 (cell.slide)
      662+ cell.slide.on: 1.0 (cell.slide, cell.slide)
         650+ cell.melt.on: 0.0 (cell.slide, cell.slide, slide.on)
         656🏁 cell.tunl.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         668🏁 cell.fred.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         674🏁 cell.zha.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         644🏁 cell.ave.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
         636🏁 cell.fade.on: 0.0 (cell.slide, cell.slide, slide.on, melt.on)
